### ISSUE TITLE
Transparent background for file icon in active tab

### ISSUE THREAD

**Issue by Gelio** [alvarosevilla95/luatab.nvim#1]
Hey! Thanks for this plugin, I've been looking for something like it as I wanted to have the icons in the tabline but I didn't want to mix tabs and buffers like other plugins do :smile: 

As I began using this plugin, I have noticed that in my theme (https://github.com/sainnhe/gruvbox-material) the background for the file icons is black and it does not match the tabline's background:

![image](https://user-images.githubusercontent.com/889383/124552904-663ef600-de34-11eb-84d8-d92dcec36d21.png)

This only happens for the active tab. The background of icons for inactive tabs fits in

Is there something we could do about it?

Once again, thanks for this plugin :+1:

**Comment by alvarosevilla95** [comment]
Ah, hadn't noticed the devicon highlight defaults to `bg1`, as I use the same color for my TabLineSel bg. Should be fixed now!

**Comment by Gelio** [comment]
Yup, looks good now:
![image](https://user-images.githubusercontent.com/889383/124592180-76b79680-de5d-11eb-9bf9-1fc70cc70d31.png)

Thanks for a quick fix :+1:
