### ISSUE TITLE
Is there a way to add the tab index?

### ISSUE THREAD

**Issue by burkettd** [alvarosevilla95/luatab.nvim#17]
Is there a way to add the tab index so I can easily switch tabs with `{tab index}gt` without counting?

**Comment by pyrho** [comment]
I have this is my config that shows the tab index in the title:
```lua
    require'luatab'.setup {
      windowCount = function(idx) return "[" .. idx .. "] " end,
    }
```

**Comment by burkettd** [comment]
That works, thanks so much @pyrho!
