### ISSUE TITLE
nvim-webdev-icons get_icon expects file extension, not &filetype

### ISSUE THREAD

**Issue by ReubenM** [alvarosevilla95/luatab.nvim#6]
```dev, devhl = require'nvim-web-devicons'.get_icon(file, vim.fn.getbufvar(bufnr, '&filetype'))```

should be 

```dev, devhl = require'nvim-web-devicons'.get_icon(file, vim.fn.expand('%:e'))```

**Comment by ReubenM** [comment]
I would submit a pull request, but there are bigger design issues where the create_component_highlight_group method is overwriting all the highlight groups with the same icon.

**Comment by alvarosevilla95** [comment]
Hey thanks for the feedback, I've applied the suggestion to use file extension properly. I'm not sure I understand your point regarding create_component_highlight_group, could you expand on the issue?

**Comment by ReubenM** [comment]
Open multiple tabs, and load different filetypes into the buffer for each tab. (for instance 3 tabs, with the files foo.lua, bar.py and baz.rb opened in the respective tabs)

Then switch between tabs. The icons for each all tabs are updated to show the same icon as the active tab irrespective of fiel type/extension. The highlight groups are all being redefined each time you switch tabs and set to use the icon for the active tab.

**Comment by ReubenM** [comment]
what I mean is that my suggested fix is not enough because it always sends the file extension of the current buffer since it doesn't apply the eval on each buffer separately. 

I hadn't looked up yet to see how to use eval on different buffers.

**Comment by ReubenM** [comment]
ok, figured it out. didn't know eval had syntax to allow it to operate on different buffers. This fixes it:

```
        dev, devhl = require'nvim-web-devicons'.get_icon(file, vim.fn.expand('#'..bufnr..':e'))
```
much simpler that I thought it would be

**Comment by alvarosevilla95** [comment]
Ahh ouch, hope my other commit didn't cause any headaches to anyone. Thank you very much for the solution!
