### ISSUE TITLE
Exclud filetypes

### ISSUE THREAD

**Issue by dchinmay2** [alvarosevilla95/luatab.nvim#7]
Can you add an option to disable the tabline for certain filetypes like startify and telescope?
If I wrote my own function I would have to write `tabName` `formatTab` and `tabline` myself

**Comment by alvarosevilla95** [comment]
Hey, check out the commit `751de09e9a8cac12591c3b6a31248b9a9b108d03`, I've tried to make things a bit more configurable, let me know if it works for you

**Comment by dchinmay2** [comment]
This is great, thanks!
